<a href="https://colab.research.google.com/github/armandossrecife/icc-2024-2/blob/main/trabalhando_vetores_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Representação de Vetores (Arrays) e Matrizes (m linhas x n colunas) - Usando LISTAS no Python

In [140]:
# Um vetor (array) de 3 elementos
v1 = [10, 20, 30]
v2 = [15.5, 21.7, 30.2]

In [141]:
print(v1)

[10, 20, 30]


In [142]:
print(v2)

[15.5, 21.7, 30.2]


## Acessar os elementos de um vetor usando seus índices

In [143]:
v1[0], v1[1], v1[2]

(10, 20, 30)

In [144]:
MATRIZ_EXEMPLO = [
    [30, 32, 40],
    [14, 20, 12],
    [20, 25, 28]
]

In [145]:
MATRIZ_EXEMPLO = [[30, 32, 40],[14, 20, 12],[20, 25, 28]]

In [146]:
print(MATRIZ_EXEMPLO)

[[30, 32, 40], [14, 20, 12], [20, 25, 28]]


In [147]:
MATRIZ_EXEMPLO[0][0]

30

In [148]:
# 1a linha
print("a(0,0): elemento(1,1)", MATRIZ_EXEMPLO[0][0])
print("a(0,1): elemento(1,2)", MATRIZ_EXEMPLO[0][1])
print("a(0,2): elemento(1,3)",MATRIZ_EXEMPLO[0][2])
# 2a linha
print("a(1,0): elemento(2,1)", MATRIZ_EXEMPLO[1][0])
print("a(1,1): elemento(2,2)", MATRIZ_EXEMPLO[1][1])
print("a(1,2): elemento(2,3)", MATRIZ_EXEMPLO[1][2])
# 3a linha
print("a(2,0): elemento(3,1)", MATRIZ_EXEMPLO[2][0])
print("a(2,1): elemento(3,2)", MATRIZ_EXEMPLO[2][1])
print("a(2,2): elemento(3,3)", MATRIZ_EXEMPLO[2][2])

a(0,0): elemento(1,1) 30
a(0,1): elemento(1,2) 32
a(0,2): elemento(1,3) 40
a(1,0): elemento(2,1) 14
a(1,1): elemento(2,2) 20
a(1,2): elemento(2,3) 12
a(2,0): elemento(3,1) 20
a(2,1): elemento(3,2) 25
a(2,2): elemento(3,3) 28


In [149]:
# 2a linha
print(MATRIZ_EXEMPLO[1][0])
print(MATRIZ_EXEMPLO[1][1])
print(MATRIZ_EXEMPLO[1][2])

14
20
12


In [150]:
# 3a linha
print(MATRIZ_EXEMPLO[2][0])
print(MATRIZ_EXEMPLO[2][1])
print(MATRIZ_EXEMPLO[2][2])

20
25
28


# Usando Álgebra Linear com vetores e matrizes de alta ordem (milhões de elementos, bilhões de elementos...)

In [151]:
import numpy

# Definição de um vetor (alta ordem) usando o Numpy

In [152]:
vetor1 = [1, 2, 3, 4, 5]
vetor2 = numpy.array(vetor1)

In [153]:
print(vetor2)

[1 2 3 4 5]


In [154]:
print(type(vetor2))

<class 'numpy.ndarray'>


In [155]:
matriz_2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [156]:
matriz_2_numpy = numpy.array(matriz_2)

In [157]:
print(matriz_2_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [158]:
print(type(matriz_2_numpy))

<class 'numpy.ndarray'>


In [159]:
vetor_sequencial = numpy.array([0, 1, 2, 3, 4, 5])

In [160]:
print(vetor_sequencial)

[0 1 2 3 4 5]


In [161]:
vetor_repetido = numpy.array([1, 1, 1, 1, 1])
print(vetor_repetido)

[1 1 1 1 1]


In [162]:
vetor_10_elementos_aleatorios = numpy.random.rand(10)
print(vetor_10_elementos_aleatorios)

[0.46372897 0.74162611 0.77883264 0.64124852 0.7035992  0.75438345
 0.90265293 0.41150593 0.19544601 0.40092713]


In [163]:
vetor_10_elementos_aleatorios[0]

0.4637289675974311

In [164]:
vetor_10_elementos_aleatorios[1]

0.7416261104326667

In [165]:
vetor_10_numeros_aleatorios = numpy.random.randint(0, 11, size=10)
print(vetor_10_numeros_aleatorios)

[2 1 6 7 9 4 4 5 6 6]


In [166]:
matriz_identidade = numpy.eye(3)

In [167]:
matriz_identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [168]:
matriz_identidade_10x10 = numpy.eye(10)

In [169]:
print(matriz_identidade_10x10)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [170]:
matriz_zeros = numpy.zeros((3, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [171]:
matriz_zeros_1000x1000 = numpy.zeros((1000, 1000))
print(matriz_zeros_1000x1000)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [172]:
matriz_uns = numpy.ones((3, 3))
print(f"matriz_uns: {matriz_uns}")

matriz_uns: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [173]:
matriz_uns_1000x1000 = numpy.ones((1000, 1000))
print(f"matriz_uns_1000x1000: {matriz_uns_1000x1000}")

matriz_uns_1000x1000: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [174]:
# Criando uma matriz com valores aleatórios
matriz_aleatoria = numpy.random.rand(2, 3)
print(f"matriz_aleatoria: {matriz_aleatoria}")

matriz_aleatoria: [[0.72233511 0.60925028 0.64740323]
 [0.56043872 0.5500561  0.51516682]]


# Operações sobre matrizes

In [175]:
# Criando dois arrays
array1 = numpy.array([1, 2, 3])
array2 = numpy.array([4, 5, 6])

# Soma
soma = array1 + array2
print(soma)  # Output: [5 7 9]

# Subtração
subtracao = array2 - array1
print(subtracao)  # Output: [3 3 3]

[5 7 9]
[3 3 3]


In [176]:
A = numpy.array([
    [1, 0, 2],
    [-1, 3, 1]
    ])

B = numpy.array([
    [3, 1],
    [2, 1],
    [1, 0]
    ])

print(f'A: {A}')
print(f'B: {B}')

A: [[ 1  0  2]
 [-1  3  1]]
B: [[3 1]
 [2 1]
 [1 0]]


In [177]:
type(A)

numpy.ndarray

In [178]:
type(B)

numpy.ndarray

In [179]:
# O produto entre as matrizes A e B
# C = A x B
import time

t1 = time.time()
C = numpy.dot(A, B)
t2 = time.time()
print(f'Tempo de execução: {t2 - t1}')
print(f'C: {C}')

Tempo de execução: 0.0013880729675292969
C: [[5 1]
 [4 2]]


# Usando funções mátemáticas do Numpy

In [180]:
print(numpy.pi)

3.141592653589793


In [181]:
round(numpy.pi, 4)

3.1416

In [182]:
# Criando um array de ângulos em radianos
vetor_angulos = numpy.array([0, numpy.pi/2, numpy.pi])
print(vetor_angulos)

[0.         1.57079633 3.14159265]


In [183]:
print("Valores em radianos")
print("1o. elemento: ", vetor_angulos[0])
print("2o. elemento: ", vetor_angulos[1])
print("3o. elemento: ", vetor_angulos[2])

Valores em radianos
1o. elemento:  0.0
2o. elemento:  1.5707963267948966
3o. elemento:  3.141592653589793


In [184]:
vetor_senos = numpy.sin(vetor_angulos)
vetor_cossenos = numpy.cos(vetor_angulos)
vetor_tangentes = numpy.tan(vetor_angulos)

In [185]:
print("Valores (radianos) do vetor SENO resultante")
print("1o. elemento: ", vetor_senos[0])
print("2o. elemento: ", vetor_senos[1])
print("3o. elemento: ", round(vetor_senos[2], 4))

Valores (radianos) do vetor SENO resultante
1o. elemento:  0.0
2o. elemento:  1.0
3o. elemento:  0.0


In [186]:
print("Valores (radianos) do vetor COSSENO resultante")
print("1o. elemento: ", vetor_cossenos[0])
print("2o. elemento: ", round(vetor_cossenos[1], 4))
print("3o. elemento: ", vetor_cossenos[2])

Valores (radianos) do vetor COSSENO resultante
1o. elemento:  1.0
2o. elemento:  0.0
3o. elemento:  -1.0


In [187]:
print("Valores (radianos) do vetor TANGENTE resultante")
print("1o. elemento: ", vetor_tangentes[0])
print("2o. elemento: ", round(vetor_tangentes[1], 4))
print("3o. elemento: ", round(vetor_tangentes[2]), 4)

Valores (radianos) do vetor TANGENTE resultante
1o. elemento:  0.0
2o. elemento:  1.633123935319537e+16
3o. elemento:  0 4


In [188]:
import numpy

# Gera uma matriz 27x12 de temperaturas randomicas
matriz_temperaturas = numpy.random.rand(27, 12) * 40
print(matriz_temperaturas)

[[ 1.55715452 34.70307133 16.48946056 20.40171453 21.49936199 29.4938836
  25.88202248 23.94527529 15.68666838 21.17489887  4.9884555  23.21297685]
 [36.73908814 27.3508438  11.52888411  0.49066275 29.5228581   4.41677815
  24.31833122 26.18065024 39.17478216 15.83540717 13.45830557  0.20463139]
 [29.69526143 38.88551798  3.09609026 25.45349035  7.47528514 15.49610301
   0.92098154  4.42265478 10.46390207 22.70852998  6.82979081 21.84648969]
 [ 4.78775872 36.26259684 27.95465071 25.84867174 18.78986589  7.96858621
  31.99269361 31.79762325  4.97125177 14.59195848  5.65305112 30.53906307]
 [22.79618214  2.16887043 10.81861262 19.97070546 21.75798496 15.98416098
  31.97703274 23.61521358 23.66331787  8.48037202 35.2086724  32.79604872]
 [ 9.99053956 20.12705835 28.85945764 33.00218868 10.40607849  2.50493403
  14.66280732 18.16780118  6.57756249  3.95912955 16.65454493 21.39007601]
 [14.24966633 35.06742839 18.3777121  36.59428929 21.93494586 23.72555629
  35.66750096  5.90910597  7.8930

In [189]:
media_temperaturas = numpy.mean(matriz_temperaturas)
desvio_padrao_temperaturas = numpy.std(matriz_temperaturas)
maximo_matriz_temperaturas = numpy.max(matriz_temperaturas)
minimo_matriz_temperaturas = numpy.min(matriz_temperaturas)

In [190]:
print("media_temperaturas: ", round(media_temperaturas, 2))
print("Desvio padrão: ", round(desvio_padrao_temperaturas, 2))
print("Máximo: ", round(maximo_matriz_temperaturas, 2))
print("Mínimo: ", round(minimo_matriz_temperaturas, 2))

media_temperaturas:  19.86
Desvio padrão:  11.44
Máximo:  39.63
Mínimo:  0.2


In [191]:
# Calculando a média, desvio padrão, máximo e mínimo
media = numpy.mean(temperaturas)
desvio_padrao = numpy.std(temperaturas)
maximo = numpy.max(temperaturas)
minimo = numpy.min(temperaturas)

print("Média:", media)
print("Desvio padrão:", desvio_padrao)
print("Valor máximo:", maximo)
print("Valor mínimo:", minimo)

Média: 20.62714211066913
Desvio padrão: 11.68304969110936
Valor máximo: 39.96675969155423
Valor mínimo: 0.02425525070567147


# Resolvendo Sistemas Lineares com o Numpy

Seja o seguinte sistema de equações:

2x + y = 8

x - y = 1

In [204]:
import numpy

# Definindo a matriz dos coeficientes e o vetor dos termos independentes
A = numpy.array([[2, 1], [1, -1]])
b = numpy.array([8, 1])

In [205]:
print('Matriz dos coeficientes')
print(A)

Matriz dos coeficientes
[[ 2  1]
 [ 1 -1]]


In [206]:
print('Vetor dos termos independentes')
print(b)

Vetor dos termos independentes
[8 1]


In [210]:
resultado = numpy.linalg.solve(A, b)
print("Solução do sistema:")
print("x =", resultado[0])
print("y =", resultado[1])

Solução do sistema:
x = 3.0
y = 2.0
